
const MINIMUM_TOP_CATEGORIES = 1;
const MINIMUM_FEATURED_APP = 1;
const MINIMUM_BANNERS = 1;
const MINIMUM_TRY_NEW_APPS = 1;
const MINIMUM_PEOPLE_ARE_LOVING_APPS = 1;

module.exports = {
  MINIMUM_BANNERS,
  MINIMUM_FEATURED_APP,
  MINIMUM_PEOPLE_ARE_LOVING_APPS,
  MINIMUM_TRY_NEW_APPS,
  MINIMUM_TOP_CATEGORIES
};
